# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ormolu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mrkkrp/ormolu-action@v4

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    needs:
      - ormolu
    if: success()
    steps:
      - uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        if: github.ref_name == 'main' && github.event_name == 'push' # don't need to login if we're not pushing
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get short commit hash
        id: hash
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.ref_name == 'main' && github.event_name == 'push' }} # only actually publish on push to main
          tags: |
            "ghcr.io/${{ github.repository_owner }}/tablebot:latest"
            "ghcr.io/${{ github.repository_owner }}/tablebot:${{ steps.hash.outputs.sha_short }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max
